# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='profile',
        ),
    ]
